## Домашка Numpy

### Ответы находятся в соседней ячейке. Задачи выполненные в первом блоке считаются выполнены, если пройден тест, т.е. ячейка выдаст True , БЕЗ FALSE!

------
### Ваш коллега создал структуру данных (см. окно ввода ответа) и передал вам в работу. Преобразуйте ее в массив NumPy и выполните следующие задания:
1.	Создайте подмассив lines, содержащий все строки со 2-й по 4-ю включительно.
2.	Создайте подмассив last_column, содержащий последний столбец исходного массива.
3.	Транспонируйте исходный массив и сохраните результат в переменную array_t.
4.	Вычислите сумму элементов исходного массива, результат сохраните в переменную array_sum.
5.	Вычислите среднее значение элементов исходного массива, результат сохраните в переменную array_avg.

In [36]:
from unittest import result

import numpy as np

some_data =  [
    [3, 8, 1, 0, 1, 2],
    [9, 2, 7, 3, 0, 4],
    [2, 5, 1, 3, 1, 8],
    [5, 1, 2, 1, 1, 0]
]

# далее запишите ваш код
some_data = np.array(some_data)
lines = some_data[1:]
last_column = some_data[::, -1]
array_t = some_data.T
array_sum = some_data.sum()
array_avg = some_data.mean()

In [37]:
print(array_avg == 2.9166666666666665)
print(array_sum == 70)

True
True


---
### Операции с массивами NumPy

#### Исходные массивы:
```python
import numpy as np
array = np.arange(10) ** 4    # Платежи по играм
array_2 = np.arange(10) ** 3  # Платежи по подпискам
```
#### Выполните последовательно следующие задания применительно к исходным массивам:
1.	Определите общую сумму дохода сразу по двум потокам. Для этого сначала сложите полученные массивы, после чего получите сумму всех элементов. Результат сохраните в переменную array_sum.
2.	Вычислите, насколько больше денег принесла продажа игр за указанный период. Результат сохраните в переменную array_difference.
3.	Сохраните 2-й элемент массива по платежам игр в переменную game_payments2.
4.	Сохраните последний элемент массива по платежам подписок в переменную subscription_last.


In [38]:
import numpy as np

array = np.arange(10) ** 4
array_2 = np.arange(10) ** 3

# далее напишите ваше решение
array_sum = sum(sum(array_2,array))
array_difference = (array - array_2).sum()
game_payments2 = array[1]
subscription_last = array_2[-1]


In [39]:
print(subscription_last == 729)

True


-----
### Решение системы линейных уравнений
Из определенного листового материала необходимо выкроить 360 заготовок типа А, 300 заготовок типа Б и 675 заготовок типа В. При этом можно применять три способа раскроя. 

Количество заготовок, получаемых из каждого листа при каждом способе раскроя, указано в таблице:
| Тип заготовки | Способ раскроя 1 | Способ раскроя 2 | Способ раскроя 3 |
|---------------|------------------|------------------|------------------|
| А             | 3                | 2                | 1                |
| Б             | 1                | 6                | 2                |
| В             | 4                | 1                | 5                |

#### Найдите решение задачи, при котором расход материала и отходы окажутся минимальными. 
#### Важно:
-	Для решения используйте модуль linalg библиотеки NumPy.
-	Ответом должен быть массив NumPy из чисел листов, необходимых на раскрой первым, вторым и третьим способом соответственно. 


In [40]:
import numpy as np

X = np.array([[3, 2, 1],
                   [1, 6, 2],
                   [4, 1, 5]])
y = np.array([360, 300, 675])

answer = np.linalg.solve(X, y)
answer


array([90., 15., 60.])

In [41]:
print(answer == [90., 15., 60.])

[False False False]


----
### Анализ массива с помощью NumPy в Python
#### Для этого задания вы можете использовать любой доступный вам набор данных. Либо можно сгенерировать NumPy массив самостоятельно. 
#### Что нужно сделать:
1.	Создайте Python-ноутбук, загрузите в него данные из csv-файла и преобразуйте в массив NumPy. Либо сгенерируйте массив самостоятельно.
2.	Получите атрибуты массива — число измерений, размеры массива, количество элементов, тип данных элементов.
3.	Потренируйтесь в выборке элемента по индексу и выполнении срезов данных массива.
4.	Потренируйтесь в выполнении математических и статистических функций библиотеки NumPy — найдите сумму элементов, среднее значение, медиану, отклонение от среднего и другие показатели, которые считаете полезными при анализе исходного массива.

In [42]:
import numpy as np

# ваш код ниже

----
## Блок 2
----

### Задача 1: Базовые операции с массивами
**Условие:**  
Создайте:  
1. Массив из 10 нулей (`arr1`)  
2. Массив из чисел от 5 до 15 (`arr2`)  
3. Массив 3x3 со случайными целыми числами от 0 до 10 (`arr3`)  


In [43]:
import numpy as np

# далее ваш код
arr1 = np.zeros(10)
arr2 = np.arange(5, 15)
arr3 = np.random.randint(0, 10, size=(3, 3))
arr3

array([[4, 3, 0],
       [6, 2, 6],
       [1, 0, 8]])

### Бродкастинг
#### Условие:
- Дан массив a = np.array([1, 2, 3]). 
- Умножьте его на число 5 и на массив b = np.array([0.5, 0.5, 0.5]) используя broadcasting.

In [44]:
import numpy as np
a = np.array([1, 2, 3])
result_a = a * 5
result_b = a * 0.5

In [45]:
print(result_a == [5, 10, 15] )
print(result_b == [0.5, 1.0, 1.5] )

[ True  True  True]
[ True  True  True]


### Маскирование
**Условие:**  
Дан массив температур `temps = np.array([-5, 12, 18, 0, -3, 25, 15])`. Замените:
- Все отрицательные температуры на 0
- Температуры от 0 до 15 на 1
- Температуры выше 15 на 2


In [46]:
import numpy as np

temps = np.array([-5, 12, 18, 0, -3, 25, 15])
#далее ваш код

temps[temps < 0] = 0
temps[(0 < temps) & (temps <= 15)] = 1
temps[temps > 15] = 2
result = temps


In [47]:
print(result == [0, 1, 2, 0, 0, 2, 1])

[ True  True  True  True  True  True  True]


### Скользящее среднее с маскированием
**Условие:**  
Для массива `data = np.array([3, 5, 2, 8, 1, 9, 4, 6])` рассчитайте 3-точечное скользящее среднее, исключая значения больше 7.

In [48]:
import numpy as np

data = np.array([3, 5, 2, 8, 1, 9, 4, 6])
#далее ваш код

kernel = np.ones(3) / 3
moving_avg = np.convolve(data[data <= 7], kernel, mode='valid')
moving_avg

array([3.33333333, 2.66666667, 2.33333333, 3.66666667])

In [49]:
print("Скользящее среднее:", moving_avg == [3.33, 3.67, 2.33, 3.67])

Скользящее среднее: [False False False False]


### Матричные операции с условиями
#### Условие:
#### Даны матрицы A = np.random.randint(0, 10, (4,4)) и B = np.random.randint(0, 10, (4,4)). Вычислите:
- Элементы, где A > B
- Сумму элементов, где (A + B) > 10

In [50]:
import numpy as np

A = np.random.randint(0, 10, (4,4))
B = np.random.randint(0, 10, (4,4))
# далее ваш код

condition1 = A[A > B]
condition2_sum = A + B
condition2_sum = condition2_sum[condition2_sum > 10]

In [51]:
print("Матрица A:\n", A)
print("Матрица B:\n", B)
print("Элементы A > B:", condition1)
print("Сумма элементов (A+B)>10:", condition2_sum)

Матрица A:
 [[1 7 0 0]
 [7 3 5 9]
 [3 6 1 2]
 [5 6 2 1]]
Матрица B:
 [[6 4 8 1]
 [6 1 3 6]
 [4 3 5 3]
 [2 7 8 5]]
Элементы A > B: [7 7 3 5 9 6 5]
Сумма элементов (A+B)>10: [11 13 15 13]


### Расширенный бродкастинг
#### Условие:
#### Создайте сетку координат для квадрата 5x5 с центром в точке (2, 2), где каждая ячейка содержит расстояние до центра.


In [52]:
import numpy as np

# далее ваш код
distances = np.arange(25).reshape(5, 5)
distances = np.sqrt((distances % 5 - 2) ** 2 + (distances // 5 - 2) ** 2)

In [53]:
print("Матрица расстояний:\n", distances)
# Центр должен быть 0, углы ≈ 2.828

Матрица расстояний:
 [[2.82842712 2.23606798 2.         2.23606798 2.82842712]
 [2.23606798 1.41421356 1.         1.41421356 2.23606798]
 [2.         1.         0.         1.         2.        ]
 [2.23606798 1.41421356 1.         1.41421356 2.23606798]
 [2.82842712 2.23606798 2.         2.23606798 2.82842712]]


### Поиск особых элементов
#### Условие:
#### В массиве arr = np.random.randint(1, 100, 20) найдите:
- Все простые числа
- Индексы локальных максимумов

In [54]:
import numpy as np

# ваш код ниже
arr = np.random.randint(1, 100, 20)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

vec_is_prime = np.vectorize(is_prime)
primes = arr[vec_is_prime(arr)]

mask_max = (arr[1:-1] > arr[:-2]) & (arr[1:-1] > arr[2:])
peak_indices = np.where(mask_max)


In [55]:
print("Массив:", arr)
print("Простые числа:", primes)
print("Индексы локальных максимумов:", peak_indices[0] + 1)

Массив: [62  6 48 15 42 78 21 71 74 16 33 54 85 22 54 81 70 34 16 33]
Простые числа: [71]
Индексы локальных максимумов: [ 2  5  8 12 15]


### Векторизованные вычисления
#### Условие:
#### Для матрицы M = np.random.rand(5,5) вычислите:
- Норму каждой строки (L2)
- Углы между всеми парами столбцов

In [56]:
import numpy as np

#ваш коде ниже

M = np.random.rand(5,5)
row_norms = np.linalg.norm(M, axis=1)

In [58]:
print("Нормы строк:", row_norms)
print("Матрица углов между столбцами (радианы):\n", angles)
# Диагональ должна быть 0 (один и тот же столбец)

Нормы строк: [1.08535875 1.02313623 1.36711692 1.24997332 1.73367557]


NameError: name 'angles' is not defined

----
## Блок 3 (Срезы)
----

### Четные и нечетные строки
**Условие:**  
Дан массив `arr = np.arange(36).reshape(6,6)`. Получите:
1. Все четные строки (0, 2, 4)
2. Все нечетные столбцы (1, 3, 5)

In [59]:
import numpy as np
arr = np.arange(36).reshape(6,6)
# ваше решение ниже

even_rows = arr[::2]
odd_cols = arr[:, 1::2]

In [60]:
print("Четные строки:\n", even_rows)
print("Нечетные столбцы:\n", odd_cols)
#Четные строки — строки с числами [[0, 1, 2, 3, 4, 5], [12, 13, 14, 15, 16, 17], [24, 25, 26, 27, 28, 29]].
#Нечетные столбцы — столбцы с числами [[1, 3, 5], [7, 9, 11], ..., [31, 33, 35]].

Четные строки:
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [24 25 26 27 28 29]]
Нечетные столбцы:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]
 [19 21 23]
 [25 27 29]
 [31 33 35]]


### Пограничные элементы
**Условие:**  
Для массива `arr = np.random.randint(0, 100, (5, 5))` извлеките:
1. Первую и последнюю строки
2. Все элементы по периметру массива


In [66]:
import numpy as np

arr = np.random.randint(0, 100, (5, 5))
first_last_rows = arr[[0, -1]]
perimeter = np.concatenate([
    arr[0, :-1], arr[:-1, -1], arr[-1, -1:0:-1], arr[-1:0:-1, 0]
])

In [67]:
print("Исходный массив:\n", arr)
print("\nПервая и последняя строки:\n", first_last_rows)
print("\nЭлементы по периметру:", perimeter)

Исходный массив:
 [[66 69 60 55 89]
 [69 77 74 56 22]
 [81 64 30 95 93]
 [74 38 94 91 33]
 [86 96 80 79 45]]

Первая и последняя строки:
 [[66 69 60 55 89]
 [86 96 80 79 45]]

Элементы по периметру: [66 69 60 55 89 22 93 33 45 79 80 96 86 74 81 69]


### Диагональные срезы
**Условие:**  
Из массива `arr = np.arange(25).reshape(5, 5)` извлеките:
1. Главную диагональ
2. Диагональ, расположенную на 1 позицию выше главной
3. Антидиагональ (из правого верхнего в левый нижний угол)

In [1]:
import numpy as np

arr = np.arange(25).reshape(5, 5)
#ваше решение ниже
main_diag = np.diag(arr)
upper_diag = np.diag(arr, k=1)
anti_diag = np.diag(arr)[::-1]

In [2]:
print("Исходный массив:\n", arr )
print("\nГлавная диагональ:", main_diag == [0, 6, 12, 18, 24] )
print("Диагональ выше главной:", upper_diag == [1, 7, 13, 19])
print("Антидиагональ:", anti_diag == [ 4, 8, 12, 16, 20 ])

Исходный массив:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Главная диагональ: [ True  True  True  True  True]
Диагональ выше главной: [ True  True  True  True]
Антидиагональ: [False False  True False False]


### Шахматный узор
**Условие:**  
Создайте шахматный узор 8x8 (0 и 1), используя срезы без циклов.

In [4]:
import numpy as np

# ваше решение ниже
chess = np.zeros((8, 8))
chess[::2, ::2] = 1
chess[1::2, 1::2] = 1

In [7]:
expected = np.array([
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1],
    [1, 0, 1, 0, 1, 0, 1, 0],
    [0, 1, 0, 1, 0, 1, 0, 1]
])

print("Созданный массив:\n", chess)
print("\nПроверка на соответствие:\n", np.all(chess == expected))

Созданный массив:
 [[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]

Проверка на соответствие:
 True


### Окно в массиве
**Условие:**
Для массива `arr = np.arange(64).reshape(8,8)` извлеките центральное окно 4x4 и проверьте его корректность.

In [14]:
import numpy as np

arr = np.arange(64).reshape(8,8)
# ваше решение ниже
center_window = arr[2:6, 2:6]
expected_top_left = arr[2, 2]
expected_top_right = arr[2, 5]
expected_bottom_left = arr[5, 2]
expected_bottom_right = arr[5, 5]

In [15]:
print("Проверка границ окна:")
print("Левый верхний угол:", center_window[0,0] == expected_top_left)  # True
print("Правый верхний угол:", center_window[0,-1] == expected_top_right)  # True
print("Левый нижний угол:", center_window[-1,0] == expected_bottom_left)  # True
print("Правый нижний угол:", center_window[-1,-1] == expected_bottom_right)  # True

# Проверка размера
print("\nПроверка размера окна:", center_window.shape == (4,4))  # True

Проверка границ окна:
Левый верхний угол: True
Правый верхний угол: True
Левый нижний угол: True
Правый нижний угол: True

Проверка размера окна: True


### Разворот подмассивов
**Условие:**
Дан массив `arr = np.arange(24).reshape(6,4)`. Необходимо:
1. Развернуть каждую вторую строку
2. Развернуть каждый третий столбец
3. Проверить корректность изменений

In [22]:
import numpy as np

arr = np.arange(24).reshape(6,4)
arr[1::2] = arr[1::2, -1::-1]
row_check = arr.copy()
arr[:, 2::3] = arr[-1::-1, 2::3]
col_check = arr


In [23]:
print("Проверка строк:\n", row_check)
print("Проверка столбцов:\n", col_check)
print("\nИтоговый массив:\n", arr)

Проверка строк:
 [[ 0  1  2  3]
 [ 7  6  5  4]
 [ 8  9 10 11]
 [15 14 13 12]
 [16 17 18 19]
 [23 22 21 20]]
Проверка столбцов:
 [[ 0  1 21  3]
 [ 7  6 18  4]
 [ 8  9 13 11]
 [15 14 10 12]
 [16 17  5 19]
 [23 22  2 20]]

Итоговый массив:
 [[ 0  1 21  3]
 [ 7  6 18  4]
 [ 8  9 13 11]
 [15 14 10 12]
 [16 17  5 19]
 [23 22  2 20]]
