In [ ]:
import numpy as np


In [8]:
arr = np.random.randint(0, 50, size=(8, 8))

In [9]:
arr

array([[28, 23, 17, 27, 47,  5, 30, 17],
       [14, 13, 42, 43, 37, 16,  5, 37],
       [12,  6, 25, 42, 30,  5,  2, 11],
       [ 7, 20, 33, 46, 39, 35, 23, 27],
       [ 7,  1, 29, 30, 49,  0, 20, 48],
       [22, 29, 39, 21, 11, 16, 19, 42],
       [ 1,  0, 35, 30, 46, 23, 20, 21],
       [29, 34, 42, 10, 12, 23, 25, 46]])

In [10]:
arr6 = arr[:6, :6]

In [11]:
print((arr6))
arr6[arr6 < 10] = arr6[arr6 < 10] * 3
print(arr6)

[[28 23 17 27 47  5]
 [14 13 42 43 37 16]
 [12  6 25 42 30  5]
 [ 7 20 33 46 39 35]
 [ 7  1 29 30 49  0]
 [22 29 39 21 11 16]]
[[28 23 17 27 47 15]
 [14 13 42 43 37 16]
 [12 18 25 42 30 15]
 [21 20 33 46 39 35]
 [21  3 29 30 49  0]
 [22 29 39 21 11 16]]


In [12]:
arr6[-1].max()

np.int64(39)